BMACE: bmace.c
	gcc -O3 -DFREQSET_PROBLEM=1 -DFREQSET_OUTPUT=2 -o fim_all bmace.c
	gcc -O3 -DFREQSET_PROBLEM=2 -DFREQSET_OUTPUT=2 -o fim_closed bmace.c
	gcc -O3 -DFREQSET_PROBLEM=3 -DFREQSET_OUTPUT=2 -o fim_maximal bmace.c

clean:
	rm -f fim_all fim_closed fim_maximal





